language: php

php:
  - 5.6
  - 7.0
  

before_install:
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - composer install

# to avoid generating magento2's files
before_script:
  - mv tests/mock/* vendor/magento/module-catalog/Api/Data

script:
  - php vendor/bin/phpunit -c ./build/phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls

env:
  global:
    - secure: "IgnP6f9Zofy13bakK3CCMCibdNJiVs4v4ybF3iHOSRdz2O8dPbXCoGjhjnk9XsIoMHX7ueLQjj1dIo1nlnWad/HjnvQ1Z15JjTEKP225KOJ/i9ZO0AdMzWPNBEa5BqX8VcW55rDzHKS+/xUTWXgbbNcl2RNHZ9PRspBZVTOwxk13quer14dk4q4pjUJYUMDsWniO1tNoZvMkOrjAzwG1jMmO69FbU86w1rsBWy4KYr9OOLtw3t6+pInx0M6dQTDQylTjbrS474JUjpxUDL0vlxJLjtsc2uzQAx/fFNO1r0Gj7F3hk3pCnyF1go2n6nFvoWdzQ/ZbGNOsYQSiLSjwHY5LwA1I6EruFCKBt4WHj7NYoiA0jaZcCPeTvR/vcgR6uXNVXLwvWdMUCDr4mz9MHSPwdsuXzv+qvGMPh+hhrFnhKphbXidhHl9ZQxo6qLz5EI4DUWZ28IQD6RHJCp6FawSZ4N8R1KYXD0JQJY0/QA79LB+7qaZv+oEG3ALOIZBz6QfdSyTPpk1XS7qyKw888vPTTF7CHlQsQyf7M3FZVKsnl6/2JrmTFwBXdS+IiZAeretPJV6iUWOyox6kC8evL/CYRWCuuI1TnKQhlJbaIWKHmjA4Wiot6TSu2b2glRmPiKKlfRGhOf0cQE43JyOYQnZUMeTylFcN5X6XopIXTAs="
    - secure: "wfkbzLf0TpHXJiltcQLUqbBAQKfGHD2DxeKOP5t7qlVN2MH8DK8EeNRIdv6Z09BNlnZFMpy7ZeUHpDLj+29FCSDkhaeAFOOcVrnCmtnPaRgm2+awglP7AM+ZJUgWNsuLFqkv6yPvWWay1eU31QTSoN4Ge2dVN0Ri1YRm3T1etaHdhOqK9iCiws/mByAEVrE1zuZFhQgntiPoXItxjuww+D03dtVslorL23/ZWN9771+lHcksIeddrfB/S4S6bfaH36A/Yc4J2+5dOuuxA22bjkqivjHfyGB6ZDmNhpWxWEk1FyBc+du9KlmKSwCNxpzhxVXiSZIK+wqUB0JIcRcTjEb9QlRhJIdtmjmMIAa0hiYxusHVzAZur2caMSHAwI+sEzMuMRlzXLL/SoqmSHYcmXYBFHoIhqFOWwDoMqNHJhXjdzrtCfY7Mj1ZIOEMFklYr1iB7IuYWClZFKHIHnXREzThADfEnM9ibvHL9joE/lxy1FjuCRECWKqoF9P6Db1HDVZzsH1/u6dCi+XZzc/+0UK0tGBG7DNahAEBjru3rUWL5134leqifWdpaZ270ggo5DJ9jDbIWVNhR9xL2UMGUPpbYT+bA5rgDVJmZGqui7WAGh20Ss0FAb2hzLL4AkVBdqhu6y1hq6IdNrQztS2abRlgGPHp2nsx01h7/PdhnTM="